In [60]:
import pandas as pd
import numpy as np

In [2]:
a=pd.read_csv('ex1.csv')

In [3]:
a

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
a=pd.read_csv('ex1.csv', header=None)

In [7]:
a

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [8]:
a.head()

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [9]:
a.tail()

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [23]:
t=pd.read_table('test.tsv')

In [24]:
t

test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [29]:
t1=pd.read_csv('test.tsv', sep='\t')

In [30]:
t1

test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [31]:
b=pd.read_csv('ex1.csv', header=None, names=['c1','c2','c3','c4','c5'])

In [32]:
b

c1  c2  c3  c4       c5
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [33]:
b['c3']

0     c
1     3
2     7
3    11
Name: c3, dtype: object

In [34]:
b[['c3','c1']]

c3 c1
0   c  a
1   3  1
2   7  5
3  11  9

In [37]:
c=pd.read_excel('ex1.xlsx', header=None)

In [38]:
c

0  1   2   3   4        5
0  NaN  a   b   c   d  message
1  0.0  1   2   3   4    hello
2  1.0  5   6   7   8    world
3  2.0  9  10  11  12      foo

In [39]:
df=pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [41]:
df[0]

Rk                 Player  Pos  Age   Tm   G  GS    MP   FG   FGA  ...   \
0      1             Quincy Acy   PF   24  NYK  68  22  1287  152   331  ...    
1      2           Jordan Adams   SG   20  MEM  30   0   248   35    86  ...    
2      3           Steven Adams    C   21  OKC  70  67  1771  217   399  ...    
3      4            Jeff Adrien   PF   28  MIN  17   0   215   19    44  ...    
4      5          Arron Afflalo   SG   29  TOT  78  72  2502  375   884  ...    
5      5          Arron Afflalo   SG   29  DEN  53  53  1750  281   657  ...    
6      5          Arron Afflalo   SG   29  POR  25  19   752   94   227  ...    
7      6          Alexis Ajinça    C   26  NOP  68   8   957  181   329  ...    
8      7         Furkan Aldemir   PF   23  PHI  41   9   540   40    78  ...    
9      8           Cole Aldrich    C   26  NYK  61  16   976  144   301  ...    
10     9      LaMarcus Aldridge   PF   29  POR  71  71  2512  659  1415  ...    
11    10            Lavoy Allen    C   25  IND  63   0  1070  141   299  ...    
12    11             Tony Allen   SG   33  MEM  63  41  1648  225   455  ...    
13    12        Al-Farouq Aminu   SF   24  DAL  74   3  1366  147   357  ...    
14    13           Lou Amundson   PF   32  TOT  53  35   937  109   255  ...    
15    13           Lou Amundson   PF   32  CLE  12   0    79    4    12  ...    
16    13           Lou Amundson   PF   32  NYK  41  35   858  105   243  ...    
17    14         Chris Andersen    C   36  MIA  60  20  1132  120   207  ...    
18    15          Alan Anderson   SG   32  BRK  74  19  1744  195   440  ...    
19    16          Kyle Anderson   SF   21  SAS  33   8   358   31    89  ...    
20    17          Ryan Anderson   PF   26  NOP  61   5  1675  291   729  ...    
21    18  Giannis Antetokounmpo   SG   20  MIL  81  71  2541  383   780  ...    
22    19        Carmelo Anthony   SF   30  NYK  40  40  1428  358   806  ...    
23    20           Joel Anthony    C   32  DET  49   0   406   36    62  ...    
24    Rk                 Player  Pos  Age   Tm   G  GS    MP   FG   FGA  ...    
25    21             Pero Antić    C   32  ATL  63   3  1037  108   296  ...    
26    22           Trevor Ariza   SF   29  HOU  82  82  2930  366   910  ...    
27    23         Darrell Arthur   PF   26  DEN  58   4   988  155   384  ...    
28    24              Ömer Aşık    C   28  NOP  76  76  1982  213   412  ...    
29    25          D.J. Augustin   PG   27  TOT  82  14  1964  258   647  ...    
..   ...                    ...  ...  ...  ...  ..  ..   ...  ...   ...  ...    
645  477        Elliot Williams   SG   25  TOT  13   0   119   14    37  ...    
646  477        Elliot Williams   SG   25  UTA   5   0    42    6    13  ...    
647  477        Elliot Williams   SG   25  NOP   8   0    77    8    24  ...    
648  478           Lou Williams   SG   28  TOR  80   0  2016  375   928  ...    
649  479        Marvin Williams   PF   28  CHO  78  37  2035  210   495  ...    
650  480            Mo Williams   PG   32  TOT  68  33  1980  341   860  ...    
651  480            Mo Williams   PG   32  MIN  41  19  1149  180   447  ...    
652  480            Mo Williams   PG   32  CHO  27  14   831  161   413  ...    
653   Rk                 Player  Pos  Age   Tm   G  GS    MP   FG   FGA  ...    
654  481        Reggie Williams   SF   28  SAS  20   0   105   15    39  ...    
655  482        Shawne Williams   SF   28  TOT  63  22  1087  121   300  ...    
656  482        Shawne Williams   SF   28  MIA  44  22   924  102   240  ...    
657  482        Shawne Williams   SF   28  DET  19   0   163   19    60  ...    
658  483            Jeff Withey    C   24  NOP  37   0   259   32    64  ...    
659  484           Nate Wolters   PG   23  TOT  21   0   247   20    57  ...    
660  484           Nate Wolters   PG   23  MIL  11   0   142   12    31  ...    
661  484           Nate Wolters   PG   23  NOP  10   0   105    8    26  ...    
662  485         Brandan Wright   PF 

In [42]:
df[0].head()

Rk         Player Pos Age   Tm   G  GS    MP   FG  FGA  ...    FT%  ORB  \
0  1     Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...   .784   79   
1  2   Jordan Adams  SG  20  MEM  30   0   248   35   86  ...   .609    9   
2  3   Steven Adams   C  21  OKC  70  67  1771  217  399  ...   .502  199   
3  4    Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...   .579   23   
4  5  Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...   .843   27   

   DRB  TRB  AST STL BLK  TOV   PF   PTS  
0  222  301   68  27  22   60  147   398  
1   19   28   16  16   7   14   24    94  
2  324  523   66  38  86   99  222   537  
3   54   77   15   4   9    9   30    60  
4  220  247  129  41   7  116  167  1035  

[5 rows x 30 columns]

In [43]:
df[0].columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [44]:
df[0].index

RangeIndex(start=0, stop=675, step=1)

In [45]:
df[0].describe()

Rk  Player  Pos  Age   Tm    G   GS   MP   FG  FGA ...    FT%  ORB  \
count   675     675  675  675  675  675  675  675  675  675 ...    650  675   
unique  493     493   12   21   32   84   81  557  327  458 ...    275  165   
top      Rk  Player   SG   23  TOT   82    0   MP   FG  FGA ...   .500    1   
freq     24      24  143   86   76   27  179   24   24   24 ...     29   30   

        DRB  TRB  AST  STL  BLK  TOV   PF  PTS  
count   675  675  675  675  675  675  675  675  
unique  293  350  249  119   98  177  214  463  
top     DRB  TRB  AST    0    0  TOV   PF  PTS  
freq     24   24   24   29   88   24   24   24  

[4 rows x 30 columns]

In [53]:
df[0][['Age','Pos','Tm']].head()

Age Pos   Tm
0  24  PF  NYK
1  20  SG  MEM
2  21   C  OKC
3  28  PF  MIN
4  29  SG  TOT

In [59]:
df[0].to_csv('testing.csv', header=False, index=False)

In [61]:
d=pd.date_range('19/10/2020', periods=7)

In [62]:
d

DatetimeIndex(['2020-10-19', '2020-10-20', '2020-10-21', '2020-10-22',
               '2020-10-23', '2020-10-24', '2020-10-25'],
              dtype='datetime64[ns]', freq='D')

In [63]:
e=pd.date_range('19/10/2020', periods=7, freq='M')

In [64]:
e

DatetimeIndex(['2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31',
               '2021-02-28', '2021-03-31', '2021-04-30'],
              dtype='datetime64[ns]', freq='M')

In [65]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [66]:
np.arange(7.0)

array([0., 1., 2., 3., 4., 5., 6.])

In [67]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [68]:
pd.Series(np.arange(2,7))

0    2
1    3
2    4
3    5
4    6
dtype: int32

In [69]:
pd.Series(np.arange(2,7), index=['a','b','c','d','e'])

a    2
b    3
c    4
d    5
e    6
dtype: int32

In [73]:
f=pd.Series(['a','b','c','d','e'],index=['a','b','c','d','e'])

In [74]:
f['c']

'c'

In [75]:
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]

In [76]:
zip(a,b,c)

In [77]:
list(zip(a,b,c))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [15]:
import numpy as np
import pandas as pd
from numpy.random import randn as rn

In [16]:
np.random.seed(100)
r=rn(5,4)

In [17]:
r

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

In [18]:
r

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

In [19]:
row=['A','B','C','D','E']
col=['W','X','Y','Z']

In [20]:
df=pd.DataFrame(r, index=row, columns=col)

In [21]:
df

W         X         Y         Z
A -1.749765  0.342680  1.153036 -0.252436
B  0.981321  0.514219  0.221180 -1.070043
C -0.189496  0.255001 -0.458027  0.435163
D -0.583595  0.816847  0.672721 -0.104411
E -0.531280  1.029733 -0.438136 -1.118318

In [22]:
df['X']

A    0.342680
B    0.514219
C    0.255001
D    0.816847
E    1.029733
Name: X, dtype: float64

In [23]:
df['new']=df['Y']+df['Z']

In [24]:
df['new']

A    0.900600
B   -0.848864
C   -0.022863
D    0.568310
E   -1.556454
Name: new, dtype: float64

In [28]:
df2=df.drop('A')

In [29]:
df2

W         X         Y         Z       new
B  0.981321  0.514219  0.221180 -1.070043 -0.848864
C -0.189496  0.255001 -0.458027  0.435163 -0.022863
D -0.583595  0.816847  0.672721 -0.104411  0.568310
E -0.531280  1.029733 -0.438136 -1.118318 -1.556454

In [30]:
df

W         X         Y         Z       new
A -1.749765  0.342680  1.153036 -0.252436  0.900600
B  0.981321  0.514219  0.221180 -1.070043 -0.848864
C -0.189496  0.255001 -0.458027  0.435163 -0.022863
D -0.583595  0.816847  0.672721 -0.104411  0.568310
E -0.531280  1.029733 -0.438136 -1.118318 -1.556454

In [31]:
df.loc[['B','C'],['Y']]

Y
B  0.221180
C -0.458027

In [32]:
df.iloc[::-1,::-1]

new         Z         Y         X         W
E -1.556454 -1.118318 -0.438136  1.029733 -0.531280
D  0.568310 -0.104411  0.672721  0.816847 -0.583595
C -0.022863  0.435163 -0.458027  0.255001 -0.189496
B -0.848864 -1.070043  0.221180  0.514219  0.981321
A  0.900600 -0.252436  1.153036  0.342680 -1.749765

In [33]:
df

W         X         Y         Z       new
A -1.749765  0.342680  1.153036 -0.252436  0.900600
B  0.981321  0.514219  0.221180 -1.070043 -0.848864
C -0.189496  0.255001 -0.458027  0.435163 -0.022863
D -0.583595  0.816847  0.672721 -0.104411  0.568310
E -0.531280  1.029733 -0.438136 -1.118318 -1.556454

In [37]:
name="My name is Md Akram"

In [38]:
df['new']=name.split()

In [39]:
df['new']

A       My
B     name
C       is
D       Md
E    Akram
Name: new, dtype: object

In [40]:
df

W         X         Y         Z    new
A -1.749765  0.342680  1.153036 -0.252436     My
B  0.981321  0.514219  0.221180 -1.070043   name
C -0.189496  0.255001 -0.458027  0.435163     is
D -0.583595  0.816847  0.672721 -0.104411     Md
E -0.531280  1.029733 -0.438136 -1.118318  Akram

In [41]:
df['E']=name.split()

In [42]:
df

W         X         Y         Z    new      E
A -1.749765  0.342680  1.153036 -0.252436     My     My
B  0.981321  0.514219  0.221180 -1.070043   name   name
C -0.189496  0.255001 -0.458027  0.435163     is     is
D -0.583595  0.816847  0.672721 -0.104411     Md     Md
E -0.531280  1.029733 -0.438136 -1.118318  Akram  Akram

In [44]:
a=[3,4,5,6]

In [46]:
np.array(a)

array([3, 4, 5, 6])

In [48]:
v=np.array([[2,3,4,5],[6,7,8,9]])

In [49]:
v

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [50]:
v.shape

(2, 4)

In [51]:
v[0][1]

3

In [56]:
m2=np.mat([2,3,5])

In [57]:
m

matrix([[2, 3, 5]])

In [58]:
m1=np.mat([6,7,9])

In [59]:
m1+m2

matrix([[ 8, 10, 14]])

In [64]:
n=np.arange(2,6,3)

In [65]:
n

array([2, 5])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
w=np.ones((3,4))

In [70]:
w

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
w+2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [75]:
mat1=np.array([[2,3,4],[5,8,9],[4,3,8]])

In [76]:
mat2=np.array([[4,6,8],[7,2,6],[7,8,1]])

In [77]:
mat1+mat2

array([[ 6,  9, 12],
       [12, 10, 15],
       [11, 11,  9]])

In [78]:
mat1-mat2

array([[-2, -3, -4],
       [-2,  6,  3],
       [-3, -5,  7]])

In [79]:
mat1@mat2

array([[ 57,  50,  38],
       [139, 118,  97],
       [ 93,  94,  58]])

In [80]:
mat1*mat2

array([[ 8, 18, 32],
       [35, 16, 54],
       [28, 24,  8]])

In [82]:
mat1**2

array([[ 4,  9, 16],
       [25, 64, 81],
       [16,  9, 64]], dtype=int32)

In [83]:
pow(mat1,2)

array([[ 4,  9, 16],
       [25, 64, 81],
       [16,  9, 64]], dtype=int32)